### PR TITLE
Updated Burgers tutorial

### PR DESCRIPTION
**Pull request by FloWsnr**
Hi guys,

This is Florian from RWTH Aachen University. I will be joining your lab for a couple of months, starting in March. Steve was so kind and already pointed me to this repository to make myself familiar with PARC.

The Burgers tutorial had some minor errors which I fixed in this pull-request, e.g. wrong ``Differentiator`` class name or missing ``app`` parameter. 
I also changed the way the paths to the data are handled. This should be easier for new people to adapt the tutorial to their system. Finally, I also put a small install section into the readme for the same reason as above.

Let me know if you don't agree with some of the things. I'm happy to adapt.

### CODE REVIEW

**Comment by JackBeerman** [comment]
Thank you Florian,

I believe Xinlun updated the name of the Differentiator class we have been using. We will need to update those in every demo notebook. Thank you for bringing this to our attention!

Feel free to make issues on the repo as well!

Best,
Jack

________________________________
From: Florian Wiesner ***@***.***>
Sent: Thursday, December 5, 2024 10:55 AM
To: baeklab/PARCtorch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [baeklab/PARCtorch] Updated Burgers tutorial (PR #27)


Hi guys,

This is Florian from RWTH Aachen University. I will be joining your lab for a couple of months, starting in March. Steve was so kind and already pointed me to this repository to make myself familiar with PARC.

The Burgers tutorial had some minor errors which I fixed in this pull-request, e.g. wrong Differentiator class name or missing app parameter.
I also changed the way the paths to the data are handled. This should be easier for new people to adapt the tutorial to their system. Finally, I also put a small install section into the readme for the same reason as above.

Let me know if you don't agree with some of the things. I'm happy to adapt.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/baeklab/PARCtorch/pull/27

Commit Summary

  *   e8e4778<https://github.com/baeklab/PARCtorch/pull/27/commits/e8e47781f1e8426f5325a097de06bfe74ae7f3e7> own install option
  *   3a252cd<https://github.com/baeklab/PARCtorch/pull/27/commits/3a252cd84d329e2c0e029d82a33b97ea2e0799c2> update burgers tutorial
  *   837a9c1<https://github.com/baeklab/PARCtorch/pull/27/commits/837a9c1e4b3cc2bd6ce4907947ba70b557b0ef9f> update readme
  *   8992a5c<https://github.com/baeklab/PARCtorch/pull/27/commits/8992a5c95d79bf4cf130c632909e6b470ade3ba7> update tutorial intro
  *   a12f601<https://github.com/baeklab/PARCtorch/pull/27/commits/a12f6010a452739dfd20e557dd53211a2b7ebf86> clean up the cell outputs
  *   7fbb5c6<https://github.com/baeklab/PARCtorch/pull/27/commits/7fbb5c63c8c809a3a03c3034b9793c9009f4f0f5> update readme

File Changes

(2 files<https://github.com/baeklab/PARCtorch/pull/27/files>)

  *   M PARCtorch/demos/Burgers.ipynb<https://github.com/baeklab/PARCtorch/pull/27/files#diff-69608f79ed8abe8f10e74736e39dd6c7482a1641dd50251c881b09582a245270> (271)
  *   M README.md<https://github.com/baeklab/PARCtorch/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5> (11)

Patch Links:

  *   https://github.com/baeklab/PARCtorch/pull/27.patch
  *   https://github.com/baeklab/PARCtorch/pull/27.diff

**Comment by FloWsnr** [comment]
Hi Jack,

> I believe Xinlun updated the name of the Differentiator class we have been using. We will need to update those in every demo notebook. Thank you for bringing this to our attention!

Yes, Xinlun mentioned that the tutorials might need some updating. If you guys don't mind, I will just go through the tutorials one by one and basically play beta tester. I will create a small merge-request for each so you can easily apply the changes in small doses.

Best,
Flo

**Comment by JackBeerman** [comment]
> Hi Jack,
> 
> > I believe Xinlun updated the name of the Differentiator class we have been using. We will need to update those in every demo notebook. Thank you for bringing this to our attention!
> 
> Yes, Xinlun mentioned that the tutorials might need some updating. If you guys don't mind, I will just go through the tutorials one by one and basically play beta tester. I will create a small merge-request for each so you can easily apply the changes in small doses.
> 
> Best, Flo

That would be great. Thank you for doing this.

Best,
Jack

**Review by JackBeerman — COMMENTED** [review]
Went through changes via VS code. Thank you Florian the notebooks are clean, use the new Differentiator name and the new training function.

**Pull request merged**
